### ISSUE TITLE
update from laravel 4.2 to 5.2

### ISSUE THREAD

**Issue by ulshamim** [redooor/redminportal#167]
Hello, You helped me a lot at the time in L4.2 to made major changes like #42 #43 #46 #64 #66 . I would like to know that is it safe to update your package and laravel? All functionalities can work as same as before after update?

**Comment by kongnir** [comment]
Hi, v0.2 supports L5.0 and v0.3 supports L5.1 LTS. There's currently no support for L5.2 yet. I've not tested on L5.2 so I'm not sure if it'll work. v0.2 and v0.3 have the same features so far, the only difference is their Laravel support and some dependencies versions.

That being said, there have been a lot of changes since v0.1. You may want to look at the UPGRADE.md on branches v0.2 and v0.3 first. Some changes may break the front end code. Do test it out on your local environment first and backup your database.

I've added some upgrade migration script to help migrate the v0.1 database to v0.2/v0.3. Do check out the UPGRADE.md file on the respective branches. Those migrations include moving image files around from old folder structure to new folder structure. So make sure you backup your files as well.

You can jump from v0.1 straight to v0.3 to support L5.1. There's no need to follow through v0.2.

**Comment by bhalsekhar** [comment]
Thanks for your clarification. I have made some changes in workbench like #64 so I just want to ask you another question that If I update you package to v0.3 then it will work or I have to make some major changes.

**Comment by ulshamim** [comment]
Thanks for your clarification. I have made some changes in workbench like #64 so I just want to ask you another question that If I update you package to v0.3 then it will work or I have to make some major changes.

**Comment by kongnir** [comment]
I see. Unfortunately, since L5.0, the 'workbench' folder has been deprecated. In v0.3, it's now within a folder 'packages' with very different folder structure (similar to the new L5 folder structure). Also, I've removed the dependency of Sentry in v0.3 because it doesn't support L5.

The migration from L4.2 to L5 will be a major change for us due to the removal of some helpers and major change in folder structure. It will not be a straight forward upgrade. If you're going to upgrade, I would suggest upgrading to L5.1 instead of L5.2, because L5.1 is LTS.

As for Redminportal, it's probably better to use it as a package (install via composer) instead of using the source directly. See README.md and follow the steps under Installation for Users.
